language: rust
dist: bionic
rust:
  - nightly

services:
  - docker

before_install:
  - docker build -t docker-dev.stackblog.io:5000/opensight_analytics_api:2

script:
  - cargo build --verbose --workspace analytics_api
  - cargo test --verbose --workspace analytics_api
  - cargo clippy --verbose --workspace analytics_api



deploy:

  provider: script
  script: bash analytics_api/image_builder.sh
  on:
    branch: master