[general]
debug = true
log_file = ""
port = 28019
address = "0.0.0.0"

[database]
connection_string = "postgresql://opensight_dev_user:2828ojgjqqMrOa8L@127.0.0.1:5432"

[user_auth]
jwt_algo = "HS256"
jwt_secret = "cBnkVpUA2YUBWtPpg2nkbI4jiP33j79hc8Ecv1hB"