language: rust
dist: bionic
rust:
  - nightly

services:
  - docker

script:
  - cargo build --verbose --workspace analytics_api
  - cargo test --verbose --workspace analytics_api
  - cargo clippy --verbose --workspace analytics_api



deploy:

  provider: script
  script: bash analytics_api/image_builder.sh
  on:
    branch: master