[general]
debug = true
log_file = ""
port = 28018
address = "0.0.0.0"
opensight_core = "https://app-dev.fynancial.de"

[database]
connection_string = "postgres://analyze_account:Glc95FLYbkgQwCy5KwUu@127.0.0.1/postgres"