version: "3.3"

services:
  postgresql:
    image: postgres:13.2-alpine
    networks:
      - cosmic_network
    expose:
      - 5432
    restart: always
    environment:
      POSTGRES_USER: analyze_account
      POSTGRES_PASSWORD: Glc95FLYbkgQwCy5KwUu
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:

networks:
  cosmic_network:
    driver: bridge