name: Rust

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: run cargo test in /analytics_api
        run: cargo test --verbose
        working-directory: analytics_api

      - name: run cargo test /error_api
        run: cargo test --verbose
        working-directory: error_api
