name: Rust

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: change dir to /analytics_api
        run: cd analytics_api

      - name: Run tests
        run: cargo test --verbose
